config/routes.rb
Rails.application.routes.draw do
  get 'answers/create'
  get 'homes/top'
  devise_for :users
  root "homes#top"
  resources :questions do
    get 'comments', on: :member
    resources :answers, only: [:create] do
      resources :comments, only: [:create]
    end
  end  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ultimate Choice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
  <div class="container">
    <%= link_to "Ultimate Choice", user_signed_in? ? questions_path : root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "投稿する", new_question_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-link nav-link" %>
          </li>
          <% else %>
          <%# 認証ページとトップページ以外でのみ表示 %>
          <% unless current_page?(root_path) || controller_path.include?('devise/') %>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
</nav>

    <div class="container">
      <% if notice %>
        <div class="alert alert-success"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger"><%= alert %></div>
      <% end %>
      
      <%= yield %>

      <footer id='footer' class='footer-bottom'>
        <div class='container'>
          <div class='row'>
            <div class='col-sm-6 col-12'>
              <div class='copyright'>
                <p>© 2025. Ultimate Choice</p>
              </div>
            </div>
          </div>
        </div>
      </footer>

    </div>
  </body>
</html>